apiVersion: v1
kind: Service
metadata:
  name: application-process
  labels:
    app: event-driven-spring-boot
    tier: application-process
spec:
  type: LoadBalancer
  ports:
  - port: 9000
  selector:
    app: event-driven-spring-boot
    tier: application-process
