apiVersion: v1
kind: Service
metadata:
  name: credit-application
  labels:
    app: event-driven-spring-boot
    tier: credit-application
spec:
  type: LoadBalancer
  ports:
  - port: 9001
  selector:
    app: event-driven-spring-boot
    tier: credit-application
