apiVersion: v1
kind: Service
metadata:
  name: credit-decision
  labels:
    app: event-driven-spring-boot
    tier: credit-decision
spec:
  type: LoadBalancer
  ports:
  - port: 9004
  selector:
    app: event-driven-spring-boot
    tier: credit-decision
