apiVersion: v1
kind: Service
metadata:
  name: customer
  labels:
    app: event-driven-spring-boot
    tier: customer
spec:
  type: LoadBalancer
  ports:
  - port: 9002
  selector:
    app: event-driven-spring-boot
    tier: customer
