apiVersion: v1
kind: Service
metadata:
  name: scoring
  labels:
    app: event-driven-spring-boot
    tier: scoring
spec:
  type: LoadBalancer
  ports:
  - port: 9003
  selector:
    app: event-driven-spring-boot
    tier: scoring
